"""time stamp

Revision ID: c40d49ac1147
Revises: bc5e707da938
Create Date: 2020-03-12 13:41:43.181933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40d49ac1147'
down_revision = 'bc5e707da938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imageDB', sa.Column('date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imageDB', 'date_time')
    # ### end Alembic commands ###
