"""image table

Revision ID: ebb4fe8b1f5f
Revises: 
Create Date: 2019-11-19 14:22:42.515268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb4fe8b1f5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.Column('machine', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imageDB_path'), 'imageDB', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imageDB_path'), table_name='imageDB')
    op.drop_table('imageDB')
    # ### end Alembic commands ###
